publify_core/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # TODO: use only in archive sidebar. See how made other system
  get ':year/:month', to: 'articles#index', year: /\d{4}/, month: /\d{1,2}/, as: 'articles_by_month', format: false
  get ':year/:month/page/:page', to: 'articles#index', year: /\d{4}/, month: /\d{1,2}/, as: 'articles_by_month_page', format: false
  get ':year', to: 'articles#index', year: /\d{4}/, as: 'articles_by_year', format: false
  get ':year/page/:page', to: 'articles#index', year: /\d{4}/, as: 'articles_by_year_page', format: false

  get 'articles.:format', to: 'articles#index', format: /rss|atom/, as: 'articles_feed'

  get 'sitemap.xml', to: 'xml#sitemap', format: 'googlesitemap'

  # CommentsController
  resources :comments, only: [:create] do
    collection do
      post :preview
    end
  end

  resources :feedback, only: :index

  # ArticlesController
  get '/live_search/', to: 'articles#live_search', as: :live_search_articles, format: false
  get '/search/:q(.:format)/page/:page', to: 'articles#search', as: 'search', defaults: { page: 1 }
  get '/search(/:q(.:format))', to: 'articles#search'
  get '/search/', to: 'articles#search', as: 'search_base', format: false
  get '/archives/', to: 'articles#archives', format: false
  get '/page/:page', to: 'articles#index', page: /\d+/, format: false
  get '/pages/*name', to: 'articles#view_page', format: false
  get 'previews(/:id)', to: 'articles#preview', format: false
  get 'previews_pages(/:id)', to: 'articles#preview_page', format: false
  get 'check_password', to: 'articles#check_password', format: false
  get 'articles/markup_help/:id', to: 'articles#markup_help', format: false
  get 'articles/tag', to: 'articles#tag', format: false

  # SetupController
  get '/setup', to: 'setup#index', format: false
  post '/setup', to: 'setup#create', format: false

  # TagsController (imitate inflected_resource)
  resources :tags, only: [:index, :create, :new]
  resources :tags, path: 'tag', only: [:show, :edit, :update, :destroy]
  get '/tag/:id/page/:page', to: 'tags#show', format: false
  get '/tags/page/:page', to: 'tags#index', format: false

  resources :authors, path: 'author', only: :show

  # ThemeController
  scope controller: 'theme', filename: /.*/ do
    get 'stylesheets/theme/:filename', action: 'stylesheets', format: false
    get 'javascripts/theme/:filename', action: 'javascripts', format: false
    get 'images/theme/:filename', action: 'images', format: false
    get 'fonts/theme/:filename', action: 'fonts', format: false
  end

  # For the tests
  get 'theme/static_view_test', format: false

  # For the statuses
  get '/notes', to: 'notes#index', format: false
  get '/notes/page/:page', to: 'notes#index', format: false
  get '/note/:permalink', to: 'notes#show', format: false

  get '/humans', to: 'text#humans', format: 'txt'
  get '/robots', to: 'text#robots', format: 'txt'

  # TODO: Remove if possible
  resources :accounts, only: [], format: false do
    collection do
      get 'confirm'
    end
  end

  namespace :admin do
    root 'dashboard#index', as: 'dashboard'

    resources :content, only: [:index, :new, :edit, :create, :update, :destroy], format: false do
      collection do
        get 'auto_complete_for_article_keywords'
        post 'autosave'
        put 'autosave'
      end
    end

    resources :feedback, only: [:index, :edit, :create, :update, :destroy], format: false do
      collection do
        post 'bulkops'
      end
      member do
        get 'article'
        post 'change_state'
      end
    end

    resources :notes, only: [:index, :show, :edit, :create, :update, :destroy], format: false

    resources :pages, only: [:index, :new, :edit, :create, :update, :destroy], format: false

    resources :post_types, only: [:index, :edit, :create, :update, :destroy], format: false

    resources :profiles, only: [:index, :update], format: false

    resources :redirects, only: [:index, :edit, :create, :update, :destroy], format: false

    resources :resources, only: [:index, :destroy], format: false do
      collection do
        post 'upload'
      end
    end

    resource :seo, controller: 'seo', only: [:show, :update], format: false

    # TODO: This should be a singular resource
    resource :settings, only: [], format: false do
      collection do
        get 'index'
        get 'display'
        get 'feedback'
        get 'write'
        post 'migrate'
        post 'update'
      end
    end

    # TODO: This should have a plural resource name
    resources :sidebar, only: [:index, :update, :destroy] do
      collection do
        put :publish
        post :sortable
      end
    end

    resources :tags, only: [:index, :edit, :create, :update, :destroy], format: false

    # TODO: Work out if post is actually used or not.
    get 'textfilters/macro_help(/:id)', to: 'textfilters#macro_help', id: nil, format: false
    post 'textfilters/macro_help(/:id)', to: 'textfilters#macro_help', id: nil, format: false

    resources :themes, only: [:index], format: false do
      collection do
        get 'preview'
        get 'switchto'
      end
    end

    resources :users, only: [:index, :new, :edit, :create, :update, :destroy], format: false
  end

  root 'articles#index'

  get '*from', to: 'articles#redirect', format: false
end

publify_core/app/models/note.rb
class Note < Content
  require 'twitter'
  require 'json'
  require 'uri'
  include PublifyGuid
  include ConfigManager

  serialize :settings, Hash

  setting :twitter_id, :string, ''
  setting :in_reply_to_status_id, :string, ''
  setting :in_reply_to_protected, :boolean, false
  setting :in_reply_to_message, :string, ''

  validates :body, presence: true
  validates :permalink, :guid, uniqueness: true

  after_create :set_permalink, :shorten_url
  before_create :create_guid

  scope :published, lambda {
    where(state: 'published').where('published_at <= ?', Time.zone.now).order(default_order)
  }
  default_scope { order('published_at DESC') }

  TWITTER_FTP_URL_LENGTH = 19
  TWITTER_HTTP_URL_LENGTH = 20
  TWITTER_HTTPS_URL_LENGTH = 21
  TWITTER_LINK_LENGTH = 22

  def set_permalink
    self.permalink = "#{id}-#{body.to_permalink[0..79]}" if permalink.blank?
    save
  end

  def categories
    []
  end

  def tags
    []
  end

  def html_preprocess(_field, html)
    PublifyApp::Textfilter::Twitterfilter.filtertext(html)
  end

  def truncate(message, length)
    if message[length + 1] == ' '
      message[0..length]
    else
      message[0..(message[0..length].rindex(' ') - 1)]
    end
  end

  def twitter_message
    base_message = body.strip_html
    if too_long?("#{base_message} (#{short_link})")
      max_length = 140 - "... (#{redirect.from_url})".length - 1
      "#{truncate(base_message, max_length)}... (#{redirect.from_url})"
    else
      "#{base_message} (#{short_link})"
    end
  end

  # FIXME: This breaks if the user changes or deletes their handle.
  def twitter_url
    File.join('https://twitter.com', user.twitter, 'status', twitter_id)
  end

  def send_to_twitter
    return false unless blog.has_twitter_configured?
    return false unless user.has_twitter_configured?

    twitter = Twitter::REST::Client.new do |config|
      config.consumer_key = blog.twitter_consumer_key
      config.consumer_secret = blog.twitter_consumer_secret
      config.access_token = user.twitter_oauth_token
      config.access_token_secret = user.twitter_oauth_token_secret
    end

    begin
      options = {}
      if in_reply_to_status_id && in_reply_to_status_id != ''
        options = { in_reply_to_status_id: in_reply_to_status_id }
        self.in_reply_to_message = twitter.status(in_reply_to_status_id).to_json
      end
      tweet = twitter.update(twitter_message, options)
      self.twitter_id = tweet.attrs[:id_str]
      save
      user.update_twitter_profile_image(tweet.attrs[:user][:profile_image_url])
      true
    rescue StandardError => e
      Rails.logger.error("Error while sending to twitter: #{e}")
      errors.add(:message, e)
      false
    end
  end

  content_fields :body

  def password_protected?
    false
  end

  def access_by?(user)
    user.admin? || user_id == user.id
  end

  def permalink_url(anchor = nil, only_path = false)
    blog.url_for(
      controller: '/notes',
      action: 'show',
      permalink: permalink,
      anchor: anchor,
      only_path: only_path)
  end

  def short_link
    path = redirect.from_path
    "#{prefix} #{path}"
  end

  def prefix
    blog.shortener_url.sub(%r{^https?://}, '')
  end

  def published?
    state == 'published'
  end

  private

  def too_long?(message)
    uris = URI.extract(message, %w(http https ftp))
    uris << prefix
    uris.each do |uri|
      payload = case uri.split(':')[0]
                when 'https'
                  '-' * TWITTER_HTTPS_URL_LENGTH
                when 'ftp'
                  '-' * TWITTER_FTP_URL_LENGTH
                else
                  '-' * TWITTER_HTTP_URL_LENGTH
                end
      message = message.gsub(uri, payload)
    end
    message.length > 140
  end
end

publify_core/app/controllers/admin/notes_controller.rb
class Admin::NotesController < Admin::BaseController
  layout 'administration'

  before_action :load_existing_notes, only: [:index, :edit]
  before_action :find_note, only: [:edit, :update, :show, :destroy]

  def index
    @note = new_note
  end

  def show
    unless @note.access_by?(current_user)
      flash[:error] = I18n.t('admin.base.not_allowed')
      redirect_to admin_notes_url
    end
  end

  def edit; end

  def create
    note = new_note

    note.state = 'published'
    note.attributes = params[:note].permit!
    note.text_filter ||= current_user.default_text_filter
    note.published_at ||= Time.zone.now
    if note.save
      if params[:push_to_twitter] && note.twitter_id.blank?
        unless note.send_to_twitter
          flash[:error] = I18n.t('errors.problem_sending_to_twitter')
          flash[:error] += " : #{note.errors.full_messages.join(' ')}"
        end
      end
      flash[:notice] = I18n.t('notice.note_successfully_created')
    else
      flash[:error] = note.errors.full_messages
    end
    redirect_to admin_notes_url
  end

  def update
    @note.attributes = params[:note].permit!
    @note.save
    redirect_to admin_notes_url
  end

  def destroy
    @note.destroy
    flash[:notice] = I18n.t('admin.base.successfully_deleted', name: 'note')
    redirect_to admin_notes_url
  end

  private

  def load_existing_notes
    @notes = Note.page(params[:page]).per(this_blog.limit_article_display)
  end

  def find_note
    @note = Note.find(params[:id])
  end

  def new_note
    this_blog.notes.build(author: current_user,
                          text_filter: current_user.text_filter)
  end
end

publify_core/app/controllers/notes_controller.rb
class NotesController < ContentController
  require 'json'

  layout :theme_layout

  after_action :set_blog_infos

  def index
    @notes = Note.published.page(params[:page]).per(this_blog.limit_article_display)

    if @notes.empty?
      @message = I18n.t('errors.no_notes_found')
      render 'notes/error', status: :ok
    end
  end

  def show
    @note = Note.published.find_by! permalink: CGI.escape(params[:permalink])

    if @note.in_reply_to_message.present?
      @reply = JSON.parse(@note.in_reply_to_message)
      render :show_in_reply
    end
  end

  private

  def set_blog_infos
    @keywords = this_blog.meta_keywords
    @page_title = this_blog.statuses_title_template.to_title(@notes, this_blog, params)
    @description = this_blog.statuses_desc_template.to_title(@notes, this_blog, params)
  end
end

publify_core/app/views/admin/notes/_form.html.erb
<%= n.hidden_field :text_filter, value: current_user.text_filter_name %>
<div class='form-group'>
  <%= n.text_area :body, {class: 'form-control', rows: '7', placeholder: t(".compose_new_note")} %>
</div>

<fieldset class="hidden-phone">
  <legend><%= t(".publish_settings") %></legend>
  <% unless twitter_available?(this_blog, current_user) %>
    <%= render 'admin/shared/twitter_alert' %>
  <% else %>
    <div class="checkbox">
      <label for="push_to_twitter">
        <%= check_box_tag 'push_to_twitter', true, true %>
        <%= t(".posse_to_twitter")%>
      </label>
    </div>
    <div class="form-group">
      <label for="note_in_reply_to_status_id"><%= t(".in_reply_to") %></label>
      <%= n.text_field :in_reply_to_status_id, class: 'form-control', placeholder: t(".tweet_id_like") %>
    </div>
  <% end %>
  <div class='form-group'>
    <label for="note_permalink"><%= t(".permanent_link") %></label>
    <%= n.text_field :permalink, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <label for='note_published_at'><%= t(".publish_at") %></label>
    <%= n.text_field :published_at, class: 'form-control datepicker',
      placeholder: t('.now'), data: { locale: I18n.locale } %>
  </div>
  <div class='form-group'>
    <hr>
    <%= link_to(t(".cancel"), {action: 'index'}) %>
    <%= t(".or") %>
    <%= submit_tag(t(".publish"), class: 'btn btn-success') %>
  </div>
</fieldset>

publify_core/app/views/admin/notes/_header.html.erb
<% content_for :page_heading do %>
  <h2>
    <i class="glyphicon glyphicon-large glyphicon-th-list"></i>
    <%= t(".notes") %>
  </h2>
<% end %>

publify_core/app/views/admin/notes/_list.html.erb
<div class='col-md-8'>
  <table class="table table-striped">
    <% if @notes.empty? %>
      <tr>
        <td colspan="2">
          <%= t("admin.notes.form.no_notes") %>
        </td>
      </tr>
    <% end %>
    <%= render @notes %>
    <%= display_pagination(@notes, 3, 'first', 'last')%>
  </table>
</div>

publify_core/app/views/admin/notes/_note.html.erb
<tr>
  <td>
    <%= h(note.body.strip_html.slice(0..140)) %>
    <div class='action'>
      <%= link_to(content_tag(:span, '', class: 'glyphicon glyphicon-pencil'), {action: 'edit', id: note.id}, {class: 'btn btn-primary btn-xs btn-action'}) %>
      <%= link_to(content_tag(:span, '', class: 'glyphicon glyphicon-trash'), admin_note_path(note), {class: 'btn btn-danger btn-xs btn-action'}) %>
      <%= link_to(content_tag(:span, '', class: 'glyphicon glyphicon-link'), note.short_url, {class: 'btn btn-success btn-xs btn-action'}) %>
    </div>
  </td>
  <td>
    <%= author_link(note)%><br>
    <small><%= l(note.published_at) %></small>
  </td>
</tr>

publify_core/app/views/admin/notes/edit.html.erb
<%= render 'header' %>

<div class='row'>
  <div class='col-md-4'>
    <%= form_for @note, url: admin_note_path(@note) do |n| %>
      <%= render 'form', n: n %>
    <% end %>
  </div>

  <%= render 'list' %>
</div>

publify_core/app/views/admin/notes/index.html.erb
<%= render 'header' %>

<div class='row'>
  <div class='col-md-4'>
    <%= form_for @note, url: admin_notes_path do |n| %>
      <%= render 'form', n: n %>
    <% end %>
  </div>

  <%= render 'list' %>
</div>

publify_core/app/views/admin/notes/show.html.erb
<% content_for :page_heading do %>
  <i class="icon-large"></i>
  <h2 class="page-title"><%= t('.destroy_confirmation') %></h2>
<% end %>

<p>
  <%= t(".are_you_sure", note: @note)%>
</p>

<%= form_for @note, url: admin_note_path(@note), method: :delete do %>
  <div class='form-actions'>
    <%= t(".action_or_other_html", first_action: link_to(t(".cancel"), {action: 'index'}), second_action: submit_tag(t(".delete"), class: "btn btn-danger")) %>
  </div>
<% end %>