publify_core/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # TODO: use only in archive sidebar. See how made other system
  get ':year/:month', to: 'articles#index', year: /\d{4}/, month: /\d{1,2}/, as: 'articles_by_month', format: false
  get ':year/:month/page/:page', to: 'articles#index', year: /\d{4}/, month: /\d{1,2}/, as: 'articles_by_month_page', format: false
  get ':year', to: 'articles#index', year: /\d{4}/, as: 'articles_by_year', format: false
  get ':year/page/:page', to: 'articles#index', year: /\d{4}/, as: 'articles_by_year_page', format: false

  get 'articles.:format', to: 'articles#index', format: /rss|atom/, as: 'articles_feed'

  get 'sitemap.xml', to: 'xml#sitemap', format: 'googlesitemap'

  # CommentsController
  resources :comments, only: [:create] do
    collection do
      post :preview
    end
  end

  resources :feedback, only: :index

  # ArticlesController
  get '/live_search/', to: 'articles#live_search', as: :live_search_articles, format: false
  get '/search/:q(.:format)/page/:page', to: 'articles#search', as: 'search', defaults: { page: 1 }
  get '/search(/:q(.:format))', to: 'articles#search'
  get '/search/', to: 'articles#search', as: 'search_base', format: false
  get '/archives/', to: 'articles#archives', format: false
  get '/page/:page', to: 'articles#index', page: /\d+/, format: false
  get '/pages/*name', to: 'articles#view_page', format: false
  get 'previews(/:id)', to: 'articles#preview', format: false
  get 'previews_pages(/:id)', to: 'articles#preview_page', format: false
  get 'check_password', to: 'articles#check_password', format: false
  get 'articles/markup_help/:id', to: 'articles#markup_help', format: false
  get 'articles/tag', to: 'articles#tag', format: false

  # SetupController
  get '/setup', to: 'setup#index', format: false
  post '/setup', to: 'setup#create', format: false

  # TagsController (imitate inflected_resource)
  resources :tags, only: [:index, :create, :new]
  resources :tags, path: 'tag', only: [:show, :edit, :update, :destroy]
  get '/tag/:id/page/:page', to: 'tags#show', format: false
  get '/tags/page/:page', to: 'tags#index', format: false

  resources :authors, path: 'author', only: :show

  # ThemeController
  scope controller: 'theme', filename: /.*/ do
    get 'stylesheets/theme/:filename', action: 'stylesheets', format: false
    get 'javascripts/theme/:filename', action: 'javascripts', format: false
    get 'images/theme/:filename', action: 'images', format: false
    get 'fonts/theme/:filename', action: 'fonts', format: false
  end

  # For the tests
  get 'theme/static_view_test', format: false

  # For the statuses
  get '/notes', to: 'notes#index', format: false
  get '/notes/page/:page', to: 'notes#index', format: false
  get '/note/:permalink', to: 'notes#show', format: false

  get '/humans', to: 'text#humans', format: 'txt'
  get '/robots', to: 'text#robots', format: 'txt'

  # TODO: Remove if possible
  resources :accounts, only: [], format: false do
    collection do
      get 'confirm'
    end
  end

  namespace :admin do
    root 'dashboard#index', as: 'dashboard'

    resources :content, only: [:index, :new, :edit, :create, :update, :destroy], format: false do
      collection do
        get 'auto_complete_for_article_keywords'
        post 'autosave'
        put 'autosave'
      end
    end

    resources :feedback, only: [:index, :edit, :create, :update, :destroy], format: false do
      collection do
        post 'bulkops'
      end
      member do
        get 'article'
        post 'change_state'
      end
    end

    resources :notes, only: [:index, :show, :edit, :create, :update, :destroy], format: false

    resources :pages, only: [:index, :new, :edit, :create, :update, :destroy], format: false

    resources :post_types, only: [:index, :edit, :create, :update, :destroy], format: false

    resources :profiles, only: [:index, :update], format: false

    resources :redirects, only: [:index, :edit, :create, :update, :destroy], format: false

    resources :resources, only: [:index, :destroy], format: false do
      collection do
        post 'upload'
      end
    end

    resource :seo, controller: 'seo', only: [:show, :update], format: false

    # TODO: This should be a singular resource
    resource :settings, only: [], format: false do
      collection do
        get 'index'
        get 'display'
        get 'feedback'
        get 'write'
        post 'migrate'
        post 'update'
      end
    end

    # TODO: This should have a plural resource name
    resources :sidebar, only: [:index, :update, :destroy] do
      collection do
        put :publish
        post :sortable
      end
    end

    resources :tags, only: [:index, :edit, :create, :update, :destroy], format: false

    # TODO: Work out if post is actually used or not.
    get 'textfilters/macro_help(/:id)', to: 'textfilters#macro_help', id: nil, format: false
    post 'textfilters/macro_help(/:id)', to: 'textfilters#macro_help', id: nil, format: false

    resources :themes, only: [:index], format: false do
      collection do
        get 'preview'
        get 'switchto'
      end
    end

    resources :users, only: [:index, :new, :edit, :create, :update, :destroy], format: false
  end

  root 'articles#index'

  get '*from', to: 'articles#redirect', format: false
end

publify_core/app/models/sidebar.rb
require 'sidebar_field'

# This class cannot be autoloaded since other sidebar classes depend on it.
class Sidebar < ApplicationRecord
  serialize :config, Hash

  belongs_to :blog

  scope :valid, ->() { where(type: SidebarRegistry.available_sidebar_types) }

  def self.ordered_sidebars
    os = []
    Sidebar.valid.each do |s|
      if s.staged_position
        os[s.staged_position] = ((os[s.staged_position] || []) << s).uniq
      elsif s.active_position
        os[s.active_position] = ((os[s.active_position] || []) << s).uniq
      end
      if s.active_position.nil? && s.staged_position.nil?
        s.destroy # neither staged nor active: destroy. Full stop.
      end
    end
    os.flatten.compact
  end

  def self.purge
    delete_all('active_position is null and staged_position is null')
  end

  def self.setting(key, default = nil, options = {})
    key = key.to_s

    return if instance_methods.include?(key)

    fields << SidebarField.build(key, default, options)

    send(:define_method, key) do
      if config.key? key
        config[key]
      else
        default
      end
    end

    send(:define_method, "#{key}=") do |newval|
      config[key] = newval
    end
  end

  def self.fields
    @fields ||= []
  end

  def self.description(desc = nil)
    if desc
      @description = desc
    else
      @description || ''
    end
  end

  def self.short_name
    to_s.underscore.split(/_/).first
  end

  def self.path_name
    to_s.underscore
  end

  def self.display_name(new_dn = nil)
    @display_name = new_dn if new_dn
    @display_name || short_name.humanize
  end

  class << self
    attr_writer :fields
  end

  def self.apply_staging_on_active!
    Sidebar.transaction do
      Sidebar.find_each do |s|
        s.active_position = s.staged_position
        s.save!
      end
    end
  end

  def publish
    self.active_position = staged_position
  end

  def html_id
    short_name + '-' + id.to_s
  end

  def parse_request(_contents, _params); end

  def fields
    self.class.fields
  end

  def fieldmap(field = nil)
    if field
      self.class.fieldmap[field.to_s]
    else
      self.class.fieldmap
    end
  end

  def description
    self.class.description
  end

  def short_name
    self.class.short_name
  end

  def display_name
    self.class.display_name
  end

  def content_partial
    "/#{self.class.path_name}/content"
  end

  def to_locals_hash
    fields.reduce(sidebar: self) do |hash, field|
      hash.merge(field.key => field.current_value(self))
    end
  end

  def admin_state
    return :active if active_position && (staged_position == active_position || staged_position.nil?)
    return :will_change_position if active_position != staged_position
    raise "Unknown admin_state: active: #{active_position}, staged: #{staged_position}"
  end
end

publify_core/app/controllers/admin/sidebar_controller.rb
class Admin::SidebarController < Admin::BaseController
  def index
    @available = SidebarRegistry.available_sidebars
    @ordered_sidebars = Sidebar.ordered_sidebars
  end

  # Just update a single active Sidebar instance at once
  def update
    @sidebar = Sidebar.where(id: params[:id]).first
    @old_s_index = @sidebar.staged_position || @sidebar.active_position
    @sidebar.update params[:configure][@sidebar.id.to_s].permit!
    respond_to do |format|
      format.js
      format.html do
        return redirect_to(admin_sidebar_index_path)
      end
    end
  end

  def destroy
    @sidebar = Sidebar.where(id: params[:id]).first
    @sidebar && @sidebar.destroy
    respond_to do |format|
      format.html { return redirect_to(admin_sidebar_index_path) }
      format.js
    end
  end

  def publish
    Sidebar.apply_staging_on_active!
    redirect_to admin_sidebar_index_path
  end

  # Callback for admin sidebar sortable plugin
  def sortable
    sorted = params[:sidebar].map(&:to_i)

    Sidebar.transaction do
      sorted.each_with_index do |sidebar_id, staged_index|
        # DEV NOTE : Ok, that's a HUGE hack. Sidebar.available are Class, not
        # Sidebar instances. In order to use jQuery.sortable we need that hack:
        # Sidebar.available is an Array, so it's ordered. I arbitrary shift by?
        # IT'S OVER NINE THOUSAND! considering we'll never reach 9K Sidebar
        # instances or Sidebar specializations
        sidebar = if sidebar_id >= 9000
                    SidebarRegistry.available_sidebars[sidebar_id - 9000].new(blog: this_blog)
                  else
                    Sidebar.valid.find(sidebar_id)
                  end
        sidebar.update(staged_position: staged_index)
      end
    end

    @ordered_sidebars = Sidebar.ordered_sidebars
    @available = SidebarRegistry.available_sidebars

    respond_to do |format|
      format.js
      format.html do
        return redirect_to admin_sidebar_index_path
      end
    end
  end
end

publify_core/app/views/admin/sidebar/_available.html.erb
<div data-sortable="sidebar_<%= 9000 + available_counter %>" class='alert alert-success draggable'>
  <h3 class='light'><%= available.display_name %></h3>
  <div class='widget-content'>
    <p><%= available.description %></p>
  </div>
</div>

publify_core/app/views/admin/sidebar/_available.json.erb
<div data-sortable="sidebar_<%= 9000 + available_counter %>" class='alert alert-success draggable'>
  <h3 class='light'><%= available.display_name %></h3>
  <div class='widget-content'>
    <p><%= available.description %></p>
  </div>
</div>

publify_core/app/views/admin/sidebar/_config.html.erb
<div id="sidebar-config" class='row'>
  <div id="available" class='col-md-6'>
    <div class='well'>
      <h3><%= t(".available_items") %></h3>
      <div id="available_box">
        <% if available_sidebars.blank? %>
        <p class='alert-message warning'><%= t(".you_have_no_plugins_installed") %>.</p>
        <% else %>
          <%= render partial: 'available', collection: available_sidebars %>
        <% end %>
      </div>
    </div>
  </div>

  <div id="cnt-active" class='col-md-6'>
    <div class='well'>
      <h3 id="hdr-active">
        <%= t(".active_sidebar_items") %>
        <%= image_tag "spinner-blue.gif", id: 'update_spinner',
          style: 'display:none;' %>
      </h3>
      <div id="active">
        <%= render 'target', ordered_sidebars: ordered_sidebars %>
      </div>
    </div>
  </div>
</div>

publify_core/app/views/admin/sidebar/_target.html.erb
<ul class="sortable" data-callback_url="<%= sortable_admin_sidebar_index_path %>">
  <% ordered_sidebars.each_with_index do |sidebar, index| %>
    <% next unless sidebar.id %>
    <%= render 'target_sidebar', sidebar: sidebar, sortable_index: index %>
  <% end %>
  <% if ordered_sidebars.empty? %>
    <li><%= t('.drag_some_plugins_here') %></li>
  <% end %>
</ul>

publify_core/app/views/admin/sidebar/_target_sidebar.html.erb
<li id="sidebar_<%= sidebar.id %>" class="sidebar_item" data-sortable="sidebar_<%= sidebar.id %>" >
  <%= link_to 'X', admin_sidebar_path(sidebar), {class: 'deletion_link', remote: true, method: :delete, :'data-confirm'=>'Are you sure?'} %>
  <%= form_tag admin_sidebar_path(sidebar.id), {remote: true, method: :put} do |f| %>
    <div class="active alert <%= class_for_admin_state(sidebar, sortable_index)%>">
      <h3 class='light'><%= sidebar.display_name %></h3>
      <div class='widget-content'>
        <p><%= sidebar.description %></p>
      </div>
    <div>
    <% sidebar.class.fields.each do |row| %>
      <%= row.line_html(sidebar) %>
    <% end %>
    <% if sidebar.class.fields.length > 0 %>
      <p>
        <%= submit_tag(t('.update'), class: 'btn btn-sm btn-success') %>
      </p>
    <% end %>
    </div>
  <% end %>
</li>

publify_core/app/views/admin/sidebar/destroy.js.erb
$("#sidebar_<%= @sidebar.id %>").remove();

publify_core/app/views/admin/sidebar/index.html.erb
<% content_for :page_heading do %>
  <i class="icon-large icon-sidebar"></i>
  <h2 class="page-title"><%= t(".sidebar") %></h2>
<% end %>

<div class='alert alert-info'>
  <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
  <p><%= t(".explain_how_its_works") %></p>
  <p><%= t(".download_more_plugins_html") %></p>
</div>
<p class='help-block'></p>

<%= form_tag(url_for(action: 'publish'), method: :put) do %>
  <div class='form-actions'>
    <%= link_to(t(".cancel"), {action: 'index'}) %>
    <%= t(".or") %>
    <%= submit_tag(t('.publish_changes'), class: 'btn btn-success') %>
  </div>
<% end %>

<div id="messages">&nbsp;</div>

<%= render 'config', available_sidebars: @available, ordered_sidebars: @ordered_sidebars %>

<%= form_tag(url_for(action: 'publish'), method: :put) do %>
  <div class='form-group'>
    <%= link_to(t(".cancel"), {action: 'index'}) %>
    <%= t(".or") %>
    <%= submit_tag(t('.publish_changes'), class: 'btn btn-success') %>
  </div>
<% end %>

publify_core/app/views/admin/sidebar/sortable.js.erb
var html = "<%= j render 'config', available_sidebars: @available, ordered_sidebars: @ordered_sidebars %>";
$("#sidebar-config").replaceWith(html);
bind_sortable();

publify_core/app/views/admin/sidebar/update.js.erb
var html = "<%= j render 'target_sidebar', sortable_index: @old_s_index, sidebar: @sidebar %>";
$("#sidebar_<%= @sidebar.id %>").replaceWith(html);